name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Hello! Welcome to Quentin's prsonal web application, thanks for submitting your first pull request. Please ensure you've followed the instructions outlined in the repos contributing guide to ensure you follow best practices employed within this repo."
